# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 276d8941078d18c84a1da1a7f93d391c062f8980e131768f996e718ba16ac5c96b156fa93d53f00bb0cf50b74ad50f7d814d5d46b0c849efc315e6f8b4326a00

test:
  secret_key_base: 8fd281a8fbda5e229e99291977675ff34e41f975607ad2fbf00de3399b8ac4b243d88bb0873ffa4015e2dee16a2cfefc39e45852a0e3694e037a6fb37756a419

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
